Repository openhab/openhabian, pull requests merged in 2020-07, with the labels that each got.

#1008 Add build image function to GitHub Actions
  .github/workflows/build-action.yml
  .github/workflows/shellcheck-action.yml
  .travis.yml
  Dockerfile.amd64-ubuntu
  build-image/first-boot.bash
  build-image/webif.bash
  build.bash
  ci-setup.bash
  functions/helpers.bash
  functions/helpers.bats
  functions/openhab.bash
  functions/openhabian.bash
  test.bash
Labels: CI-Pipeline

#1030 Verify signature of Raspberry Pi OS image.
  build.bash
  functions/zram.bash
Labels: CI-Pipeline, enhancement

#990 Continue Standardization and Rewrite
  .github/issue_template.md
  CONTRIBUTING.md
  LICENSE.md
  NEWS.md
  build-image/first-boot.bash
  build.bash
  docker-tests/entry.sh
  docs/NEWSLOG.md
  docs/exim.md
  functions/backup.bash
  functions/config.bash
  functions/ext-storage.bash
  functions/helpers.bash
  functions/influxdb+grafana.bash
  functions/influxdb+grafana.bats
  functions/java-jre.bash
  functions/menu.bash
  functions/nodejs-apps.bash
  functions/openhab.bash
  functions/openhabian.bash
  functions/packages.bash
  functions/passwords.bash
  functions/system.bash
  functions/vpn.bash
  functions/wifi.bash
  functions/zram.bash
  functions/zram.bats
  includes/azul_zulu_license.md
  includes/bash.bashrc
  includes/frontail-preset.json
  openhabian-setup.sh
  openhabian.conf.dist
  test.bash
Labels: base system, enhancement

#1053 Avoid cleaning JDK security directory on CEK setup
  functions/java-jre.bash
  functions/system.bash
Labels: bug, java

#1064 Reinstall NodeJS if on older version
  functions/nodejs-apps.bash
Labels: optional component
