Repository openhab/openhabian, pull requests merged in 2020-09, with the labels that each got.

#1109 Fix FIND3 install zram integration
  functions/find.bash
Labels: bug, optional component

#1111 Basic 'includes/' changes for OH3
  includes/bash_profile
  includes/frontail-preset.json
  includes/frontail-theme.css
  includes/frontail.service
  includes/mount_template
  includes/multitail.openhab.conf
  includes/openhab-override.conf
  includes/openhab2-override.conf
  includes/smb.conf
  includes/ztab
Labels: openHAB related

#1055 Finish Standardization and Rewrite
  .travis.yml
  build-image/first-boot.bash
  build-image/openhabian.pi-raspios32.conf
  build.bash
  functions/backup.bash
  functions/config.bash
  functions/ext-storage.bash
  functions/find.bash
  functions/helpers.bash
  functions/influxdb+grafana.bash
  functions/influxdb+grafana.bats
  functions/java-jre.bash
  functions/java-jre.bats
  functions/menu.bash
  functions/nodejs-apps.bash
  functions/nodejs-apps.bats
  functions/openhab.bash
  functions/openhabian.bash
  functions/packages.bash
  functions/packages.bats
  functions/passwords.bash
  functions/system.bash
  functions/vpn.bash
  functions/wifi.bash
  functions/zram.bash
  functions/zram.bats
  includes/amanda.conf-template
  includes/amanda.conf_template
  includes/dashboard-imagedata
  includes/mount_template
  includes/update-exim4.conf.conf-template
  includes/ztab
  openhabian-setup.sh
Labels: base system, enhancement

#1120 Revert package installed check after #1055
  functions/backup.bash
  functions/find.bash
  functions/helpers.bash
  functions/influxdb+grafana.bash
  functions/java-jre.bash
  functions/nodejs-apps.bash
  functions/openhab.bash
  functions/packages.bash
  functions/system.bash
  functions/wifi.bash
  functions/zram.bash
Labels: bug

#1124 Use lite image for arm64 builds
  .github/workflows/build-action.yml
  build.bash
Labels: CI-Pipeline, new

#1126 Turn cronjobs into systemd timers (FireMotD, Amanda)
  functions/backup.bash
  functions/packages.bash
  includes/amandaBackupDB.service-template
  includes/amandaBackupDB.timer
  includes/amdump.service-template
  includes/amdump.timer
  includes/firemotd.service
  includes/firemotd.timer
Labels: nice to have

#1128 Remove menu 6X
  functions/menu.bash
Labels: base system

#1144 Set MQTT values from default file for FIND3
  functions/find.bash
  includes/find3server.service
Labels: optional component
