Repository openhab/openhabian, pull requests merged in 2021-02, with the labels that each got.

#1454 Update frontail themes to match OH3 UI
  functions/nodejs-apps.bash
  includes/frontail-theme.css
  includes/frontail-theme_dark.css
  includes/frontail/bootstrap.min.css
  includes/frontail/frontail-preset.json
  includes/frontail/frontail-preset_dark.json
  includes/frontail/frontail-theme.css
  includes/frontail/frontail-theme_dark.css
  includes/frontail/frontail.service
  includes/frontail/index.html
Labels: enhancement

#1458 Allow custom logs to be added to frontail
  build-image/openhabian.conf
  build-image/openhabian.pi-raspios32.conf
  build-image/openhabian.pi-raspios64beta.conf
  functions/menu.bash
  functions/nodejs-apps.bash
  functions/nodejs-apps.bats
  includes/frontail/frontail-preset.json
  includes/frontail/frontail-preset_dark.json
  includes/frontail/frontail-theme_dark.css
  openhabian-setup.sh
  openhabian.conf.dist
Labels: enhancement, new, nice to have, optional component

#1459 Standardize systemctl timers
  functions/backup.bash
  functions/packages.bash
  includes/amandaBackupDB.service-template
  includes/amandaBackupDB.timer
  includes/amdump.service-template
  includes/amdump.timer-template
  includes/firemotd.service
  includes/firemotd.timer
  includes/homegear-management.service
  includes/sdrawcopy.service-template
  includes/sdrawcopy.timer
  includes/sdrsync.service-template
  includes/sdrsync.timer
  includes/storage.mount-template
Labels: nice to have

#1468 Make Amanda backup mounted subdirectories properly
  functions/backup.bash
  functions/zram.bash
  includes/amanda.conf-template
Labels: enhancement, nice to have, optional component

#1470 Mirror 3rd partition if it exists
  functions/backup.bash
Labels: enhancement, nice to have
