Repository openhab/openhabian, pull requests merged in 2021-09, with the labels that each got.

#1585 Partial config restore option
  functions/backup.bash
  functions/menu.bash
Labels: enhancement, openHAB related

#1584 Add option to en/disable framebuffer on RPi
  build-image/openhabian.conf
  build-image/openhabian.pi-raspios32.conf
  build-image/openhabian.pi-raspios64beta.conf
  functions/menu.bash
  functions/system.bash
Labels: hardware support

#1586 Introduce and transition to `XXX_is_installed`
  functions/backup.bash
  functions/helpers.bash
  functions/influxdb+grafana.bash
  functions/nodejs-apps.bash
  functions/openhabian.bash
  functions/packages.bash
  functions/system.bash
Labels: base system, dependencies
