Repository openhab/openhabian, pull requests merged in 2021-01, with the labels that each got.

#1344 Include HABApp
  functions/habapp.bash
  functions/habapp.bats
  functions/menu.bash
  includes/habapp.service
Labels: new, openHAB related, optional component

#1338 Dynamically generate the login screen
  includes/bash_profile
  includes/openhab2logo
  includes/openhablogo
Labels: enhancement

#1427 store_in_config() of backup parameter
  build-image/openhabian.conf
  build-image/openhabian.pi-raspios32.conf
  build-image/openhabian.pi-raspios64beta.conf
  functions/auth.bash
  functions/backup.bash
  functions/config.bash
  functions/ext-storage.bash
  functions/find.bash
  functions/influxdb+grafana.bash
  functions/openhab.bash
  functions/openhabian.bash
  functions/packages.bash
  functions/system.bash
  functions/vpn.bash
  functions/wifi.bash
  functions/zram.bash
  openhabian-setup.sh
  openhabian.conf.dist
Labels: base system, nice to have

#1428 Remove Java 8 functionality from codebase
  .github/workflows/installation-action.yml
  functions/java-jre.bash
  functions/java-jre.bats
Labels: java

#1430 Fix BATS error
  .github/workflows/bats-action.yml
  .github/workflows/installation-action.yml
  Dockerfile.rpi4-BATS
  Dockerfile.ubuntu-BATS
  functions/habapp.bats
  functions/vpn.bats
  functions/zram.bats
Labels: CI-Pipeline

#1442 Fix IP generation for tiles
  functions/openhab.bash
Labels: bug, nice to have, optional component

#1443 Update all documentation for clarity and accuracy
  .github/issue_template.md
  CONTRIBUTING.md
  NEWS.md
  README.md
  build-image/openhabian.conf
  build-image/openhabian.pi-raspios32.conf
  build-image/openhabian.pi-raspios64beta.conf
  docs/NEWSLOG.md
  docs/openhabian-DEBUG.md
  docs/openhabian-amanda.md
  docs/openhabian-exim.md
  docs/openhabian.md
  functions/backup.bash
  functions/ext-storage.bash
  functions/find.bash
  functions/helpers.bash
  functions/menu.bash
  functions/openhab.bash
  functions/openhabian.bash
  functions/system.bash
  functions/vpn.bash
  functions/zram.bash
  functions/zram.bats
  includes/ztab
  openhabian.conf.dist
Labels: documentation, enhancement
